/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PrintSystems;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PrintSys extends javax.swing.JFrame {

    /**
     * Creates new form PrintSys
     */
    public PrintSys() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        txtTelephone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRef = new javax.swing.JTextField();
        txtCourseCode = new javax.swing.JTextField();
        txtCourseTitle = new javax.swing.JTextField();
        txtStudentID = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        txtDateofBirth = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        btnAddRecord = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Print Records");
        setPreferredSize(new java.awt.Dimension(1360, 800));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 255), 8));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("How To Print Record in Java NetBeans");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 860, 100);

        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane1.setViewportView(txtReceipt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 140, 390, 330);

        txtTelephone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTelephone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(txtTelephone);
        txtTelephone.setBounds(240, 430, 220, 37);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Telephone");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 430, 180, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Reference No");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 150, 180, 32);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Course Code");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 190, 180, 32);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Course Title");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 230, 180, 32);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Student ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 270, 180, 32);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Student Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 310, 180, 32);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Date of Birth");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 350, 180, 32);

        txtRef.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtRef.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(txtRef);
        txtRef.setBounds(240, 150, 220, 37);

        txtCourseCode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtCourseCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(txtCourseCode);
        txtCourseCode.setBounds(240, 190, 220, 37);

        txtCourseTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtCourseTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(txtCourseTitle);
        txtCourseTitle.setBounds(240, 230, 220, 37);

        txtStudentID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtStudentID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(txtStudentID);
        txtStudentID.setBounds(240, 270, 220, 37);

        txtStudentName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtStudentName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(txtStudentName);
        txtStudentName.setBounds(240, 310, 220, 37);

        txtDateofBirth.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtDateofBirth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(txtDateofBirth);
        txtDateofBirth.setBounds(240, 350, 220, 37);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Address");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 390, 180, 32);

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(txtAddress);
        txtAddress.setBounds(240, 390, 220, 37);

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint);
        btnPrint.setBounds(250, 510, 150, 45);

        btnAddRecord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddRecord.setText("Add Record");
        btnAddRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddRecord);
        btnAddRecord.setBounds(20, 510, 180, 40);

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(710, 510, 150, 40);

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(490, 510, 150, 45);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        frame=new JFrame();
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","PrintSystems",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtReceipt.setText("");
        txtRef.setText("");
        txtCourseCode.setText("");
        txtCourseTitle.setText("");
        txtStudentID.setText("");
        txtStudentName.setText("");
        txtDateofBirth.setText("");
        txtAddress.setText("");
        txtTelephone.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            txtReceipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PrintSys.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnAddRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRecordActionPerformed
        txtReceipt.append("\t\t Student Records \n\n" + 
                
                "Reference No:\t\t\t" + txtRef.getText()+
                "\n===============================================\n" +
                "Course Code:\t\t\t"+txtCourseCode.getText()+ "\n\n" +
                "Course Title:\t\t\t"+txtCourseTitle.getText()+ "\n\n" +
                "Student ID:\t\t\t"+txtStudentID.getText()+ "\n\n" +
                "Student Name:\t\t\t"+txtStudentName.getText()+ "\n\n" +
                "Date of Birth:\t\t\t"+txtDateofBirth.getText()+ "\n\n" +
                "Address:\t\t\t"+txtAddress.getText()+ "\n\n" +
                "Telephone:\t\t\t"+txtTelephone.getText()+ "\n\n" +
                "============================================"
                
                
                
                
                
                
                
                
                
                
                );
        
        
        
    }//GEN-LAST:event_btnAddRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintSys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRecord;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtCourseTitle;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextArea txtReceipt;
    private javax.swing.JTextField txtRef;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
